pipeline {
   agent {
      

    environment {
        IMAGE_NAME = 'sammielas/jenkins-flask-app'
        IMAGE_TAG = "${IMAGE_NAME}:${env.GIT_COMMIT}"
        
    }

    
    stages {

        // stage('Setup') {
        //     steps {
        //          sh '''
        //             python3 -m venv /tmp/venv
        //             . /tmp/venv/bin/activate
        //             pip install -r ./04-docker/requirements.txt
        //         '''
        //     }
        // }
        // stage('Test') {
        //     steps {
        //            sh '''
        //             . /tmp/venv/bin/activate
        //             echo "Running tests..."
        //             pytest
                    
        //         '''
        //     }
        // }

        stage('Login to docker hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh 'echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin'}
                echo 'Login successfully'
            }
        }

        stage('Build Docker Image')
        {
            steps
            {
                sh 'docker build -t ${IMAGE_TAG} ./04-docker/Dockerfile'
                echo "Docker image build successfully"
                sh 'docker image ls'
                
            }
        }

        stage('Push Docker Image')
        {
            steps
            {
                sh 'docker push ${IMAGE_TAG}'
                echo "Docker image push successfully"
            }
        }      
    }
}
}
